export const ZH_CN_COPY = {
  settings: '设置',
  closeSettings: '关闭设置',
  tutorial: '教程',
  openTutorial: '打开教程',
  closeTutorial: '关闭教程',
  tutorialTitle: '快速上手',
  tutorialIntro: '按顺序完成这些步骤，就可以把手机控制任务交给 Agent 执行。',
  tutorialSteps: [
    {
      title: '连接 Android 设备',
      body: '打开 USB 调试，用数据线连接手机，然后在设备面板点击连接并在手机上授权。',
    },
    {
      title: '配置模型',
      body: '在模型设置里填写 Base URL、API Key、Model，并选择适合当前模型的动作协议。',
    },
    {
      title: '发送任务',
      body: '在聊天区输入明确目标，例如打开设置并进入 Wi-Fi 页面；发送后会自动截图并请求下一步动作。',
    },
    {
      title: '观察和接管',
      body: '运行中可查看待处理动作、步骤详情和运行日志；遇到敏感操作或验证码时可人工接管。',
    },
  ],
  tutorialNotesTitle: '使用建议',
  tutorialNotes: [
    '先用简单任务确认截图、坐标和文本输入都正常。',
    '登录、支付、删除、授权等高风险流程建议保持人工确认。',
    '常用应用可以在设置里编辑 App Cards，Secret 和 Custom Tools 也只保存在本机浏览器。',
  ],
  tutorialFaqTitle: '常见问题',
  tutorialFaqItems: [
    {
      question: '连接不上设备怎么办？',
      answer:
        '如果连接不上，请在终端输入 adb kill-server，然后重新连接设备。也请确认浏览器支持 WebUSB、手机已开启 USB 调试，并在手机上完成授权。',
    },
    {
      question: '为什么 Agent 没有继续执行？',
      answer:
        '检查 Base URL、API Key、Model 和动作协议是否匹配；也可以运行 Doctor 查看模型与设备连接状态。',
    },
    {
      question: '点击位置不准怎么办？',
      answer:
        '先手动截图确认画面和坐标正常。任务运行时会把模型截图坐标映射回设备原始坐标。',
    },
    {
      question: '中文输入或清空文本失败怎么办？',
      answer:
        '在主页左侧工具区使用“启用 ADB 文本输入”安装或启用 ADB Keyboard，并在设备选项里开启“文本输入使用 ADB 键盘”。',
    },
    {
      question: '登录、支付或验证码怎么处理？',
      answer:
        '保持敏感动作确认开启；遇到验证码、密码、支付、删除或授权等高风险流程时人工接管。',
    },
  ],
  agentContextRestored: '已恢复 Agent 上下文',
  agentContextRestoreSkipped: '已跳过 Agent 上下文恢复',
  connectDeviceTask: '连接设备',
  captureScreenTask: '截图',
  deviceConnected: '设备已连接',
  deviceDisconnected: '设备已断开',
  disconnectDeviceTask: '断开设备',
  executeActionTask: '执行动作',
  executedAction: (preview: string) => `已执行 ${preview}`,
  failedAction: (preview: string) => `执行失败 ${preview}`,
  failedToDownloadAdbKeyboard: (status: number) => `下载 ADB 键盘 APK 失败：HTTP ${status}。`,
  language: '语言',
  languageSystem: '系统默认',
  languageChinese: '中文',
  languageEnglish: 'English',
  appDescription:
    '基于浏览器的 Android 自动化控制台，支持 WebADB 和 OpenAI 兼容视觉模型。',
  githubRepository: 'GitHub 仓库',
  repositoryStats: '仓库统计',
  stars: '星标',
  forks: '复刻',
  openIssues: '开放问题',
  githubStatsError: '暂时无法加载 GitHub 统计。',
  theme: '主题',
  themeSystem: '系统',
  themeLight: '浅色',
  themeDark: '深色',
  localCache: '本地缓存',
  localCacheUsage: '本地缓存占用',
  localCacheLoading: '正在检查...',
  localCacheUnavailable: '当前浏览器不可用',
  localCacheError: '无法读取缓存占用',
  localCacheUsageOf: (usage: string, quota: string) => `${usage} / ${quota}`,
  localCacheUsageOnly: (usage: string) => `已使用 ${usage}`,
  dataManagement: '数据管理',
  dataManagementShort: '数据',
  settingsPreferences: '偏好设置',
  settingsPreferencesShort: '偏好',
  settingsResources: '资源配置',
  settingsResourcesShort: '资源',
  settingsProjectInfo: '项目信息',
  settingsProjectInfoShort: '项目',
  appVersion: '版本号',
  clearChatHistory: '清空聊天记录',
  clearRunLog: '清空运行日志',
  chatHistoryCleared: '聊天记录已清空',
  appCards: 'App Cards',
  appCardsJson: 'App Cards JSON',
  resetAppCards: '重置',
  secrets: '密钥',
  secretsJson: '密钥 JSON',
  customTools: '自定义工具',
  customToolsJson: '自定义工具 JSON',
  actionTools: '动作工具',
  actionToolsHelp:
    '可以逐个开启或关闭工具。关闭后模型不会看到该工具；如果队列里的旧动作仍尝试调用，也会被本地拦截。',
  actionToolEnabled: '已开启',
  actionToolDisabled: '已关闭',
  actionToolToggle: (name: string) => `切换${name}`,
  actionToolsSummary: (enabled: number, total: number) => `${enabled}/${total} 已开启`,
  actionToolSearch: '搜索动作工具',
  actionToolSearchPlaceholder: '搜索工具...',
  actionToolSearchClear: '清空工具搜索',
  actionToolFilter: '动作工具筛选',
  actionToolFilterAll: '全部',
  actionToolFilterEnabled: '已开启',
  actionToolFilterDisabled: '已关闭',
  noActionToolSearchResults: (query: string) => `没有匹配“${query}”的工具`,
  noActionToolsInFilter: (filter: 'all' | 'disabled' | 'enabled') =>
    filter === 'disabled' ? '没有已关闭的工具。' : '当前视图没有工具。',
  memory: '记忆功能',
  memoryHelp: '允许 WebDroid 保存 note/remember 里的短文本事实，并在后续任务中本地复用。',
  configurationPanel: '配置',
  collapseConfigurationPanel: '收起配置面板',
  expandConfigurationPanel: '展开配置面板',
  openConfigurationSection: (section: string) => `打开${section}`,
  webUsbReady: '可用',
  webUsbMissing: '不可用',
  model: '模型',
  noModel: '未设置模型',
  modelSettings: '模型设置',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  showApiKey: '显示 API Key',
  hideApiKey: '隐藏 API Key',
  reasoningEffort: '思考深度',
  reasoningEffortDefault: '服务默认',
  reasoningEffortNone: '无',
  reasoningEffortMinimal: '最小',
  reasoningEffortLow: '低',
  reasoningEffortMedium: '中',
  reasoningEffortHigh: '高',
  reasoningEffortXHigh: '极高',
  actionProtocol: '动作协议',
  actionProtocolWebDroidJson: 'WebDroid JSON',
  actionProtocolOpenAutoGlm: 'Open-AutoGLM 函数',
  actionProtocolMobilerunXml: 'mobilerun XML',
  streamModelResponses: '流式模型响应',
  device: '设备',
  noDevice: '无设备',
  deviceDetails: '设备详情',
  serial: '序列号',
  currentApp: '当前应用',
  unknownApp: '未知',
  package: '包名',
  activity: 'Activity',
  keyboard: '键盘',
  usbDebuggingRequired: '需要 USB 调试',
  connect: '连接',
  adbConnectionHelpLabel: 'ADB 连接帮助',
  adbConnectionHelpText: '如果连接不上，请在终端输入 adb kill-server，然后重新连接设备。',
  disconnect: '断开',
  capture: '截图',
  configureTextInput: '启用 ADB 文本输入',
  adbKeyboardConfigured: 'ADB 文本输入已启用',
  tools: '工具',
  runDoctor: '运行 Doctor',
  doctorChecks: 'Doctor 检查',
  doctorSummary: 'Doctor 摘要',
  installedApps: '已安装应用',
  closeInstalledApps: '关闭已安装应用',
  appSearch: '搜索应用',
  clearAppSearch: '清空应用搜索',
  launchApp: '启动',
  launchInstalledApp: (name: string) => `启动 ${name}`,
  noInstalledApps: '没有找到应用',
  noAppSearchResults: (query: string) => `没有匹配“${query}”的应用`,
  deviceOptions: '设备选项',
  directCommands: '直接设备命令',
  directCommand: '直接设备命令',
  tapX: '点击 X',
  tapY: '点击 Y',
  runTap: '执行点击',
  swipeFromX: '起点 X',
  swipeFromY: '起点 Y',
  swipeToX: '终点 X',
  swipeToY: '终点 Y',
  runSwipe: '执行滑动',
  directText: '文本',
  runType: '执行输入',
  runBack: '返回',
  runHome: '主页',
  runEnter: '回车',
  screenBlackoutDuringAutoControl: '自动控制时黑屏',
  screenBlackoutDuringAutoControlHelp:
    '自动运行时把 Android 亮度临时设为 0，结束后恢复原亮度。',
  useAdbKeyboard: '文本输入使用 ADB 键盘',
  confirmSensitiveActions: '确认敏感动作',
  unrestrictedMode: '完全无限制模式',
  sensitiveActionTitle: '请求执行敏感动作',
  sensitiveActionPrompt: '是否执行？',
  actionSettle: '动作等待 (ms)',
  doubleTapInterval: '双击间隔 (ms)',
  keyboardStep: '键盘步进 (ms)',
  supportedActions: '支持的动作',
  capabilities: [
    '启动',
    '点击',
    '输入',
    '滑动',
    '返回',
    '主页',
    '长按',
    '双击',
    '等待',
    '连续动作',
    '重复动作',
    '接管',
  ],
  actionNames: {
    back: '返回',
    call_api: '调用 API',
    custom_tool: '自定义工具',
    done: '完成',
    double_tap: '双击',
    home: '主页',
    input_text: '输入文本',
    interact: '人工交互',
    key: '按键',
    launch: '启动',
    long_press: '长按',
    note: '记录',
    open_url: '打开链接',
    paste: '粘贴',
    repeat: '重复动作',
    sequence: '连续动作',
    set_clipboard: '设置剪贴板',
    swipe: '滑动',
    take_over: '接管',
    tap: '点击',
    type_secret: '输入密钥',
    view_screenshot: '查看旧截图',
    wait: '等待',
  },
  androidScreenshot: 'Android 截图',
  expandedAndroidScreenshot: '展开的 Android 截图',
  screenshotInteractionLayer: '截图交互层',
  runGeneratedAction: '执行生成的动作',
  clearGeneratedAction: '清除生成的动作',
  openScreenshotFor: (title: string) => `打开截图：${title}`,
  screenshotDialogFor: (title: string) => `${title}预览`,
  closeScreenshotPreview: '关闭截图预览',
  screenshotZoomControls: '截图缩放控件',
  zoomInScreenshot: '放大截图',
  zoomOutScreenshot: '缩小截图',
  resetScreenshotZoom: '重置截图缩放',
  showPhoneFullscreen: '全屏显示手机',
  exitPhoneFullscreen: '退出手机全屏',
  fullscreenPhonePreview: '全屏手机预览',
  noScreenshot: '暂无截图',
  noScreenshotHint: '连接设备并截图后会显示当前画面',
  chat: '聊天',
  history: '历史记录',
  openHistorySidebar: '打开历史记录侧边栏',
  closeHistorySidebar: '关闭历史记录侧边栏',
  recentChats: '最近聊天',
  historyEmpty: '暂无聊天记录。',
  historyNoMatches: '没有匹配的聊天。',
  historyNoMatchesForQuery: (query: string) => `没有匹配“${query}”的聊天`,
  historySearchAria: '搜索聊天记录',
  historySearchPlaceholder: '搜索历史...',
  historySearchClear: '清除历史搜索',
  openHistoryThread: (title: string) => `打开聊天：${title}`,
  deleteHistoryThread: (title: string) => `删除聊天：${title}`,
  conversation: '对话',
  sessionState: '会话状态',
  sessionStatusIdle: '空闲',
  sessionStatusRunning: '运行中',
  sessionStatusAwaitingReview: '待确认',
  sessionStatusAwaitingTakeover: '需接管',
  sessionStatusDone: '完成',
  sessionStatusStopped: '已停止',
  sessionStatusError: '错误',
  sessionStep: (step: number) => `第 ${step} 步`,
  queuedMessages: (count: number) => `${count} 条排队`,
  contextCompactedThroughStep: (step: number) => `已压缩到 #${step}`,
  noMessages: '暂无消息',
  quickStartPrompts: [
    '打开设置并进入 Wi-Fi',
    '截图并告诉我当前页面',
    '返回主页',
  ],
  chatMessage: '聊天消息',
  chatPlaceholder: '发送后续指令...',
  loopGuardStopped: '运行因循环保护停止',
  manualTakeoverRequested: '请求人工接管',
  maxStepsReached: '已达到最大步数',
  send: '发送',
  stopRun: '停止运行',
  scrollToLatest: '滚动到最新',
  newChat: '新聊天',
  newChatStarted: '已开始新聊天',
  noAdbKeyboardDownloadSupport: '当前浏览器无法下载 ADB 键盘 APK。',
  typeMessageFirst: '请先输入消息。',
  runAgentTask: '运行任务',
  screenBlackoutStartFailed: '黑屏模式开启失败',
  screenBlackoutRestoreFailed: '屏幕亮度恢复失败',
  runStopped: '运行已停止',
  previousRunInterrupted: '上次运行在完成前被中断。',
  waitForCurrentRun: '请等待当前运行结束。',
  maxSteps: '最大步数',
  pendingAction: '待处理动作',
  screenCaptured: '已截图',
  step: '步骤',
  stepPreview: (index: number, preview: string) => `步骤 ${index}：${preview}`,
  stepAction: '动作',
  stepResult: '结果',
  stepDetails: '详情',
  stepTool: '工具',
  stepExecutionResult: '执行结果',
  stepModelOutput: '模型输出',
  stepParsedAction: '解析动作',
  stepTiming: (totalMs: number) => `耗时 ${totalMs} ms`,
  stepTimingSeconds: (seconds: number) => `${seconds} 秒`,
  stepTimingLessThanSecond: '<1 秒',
  stepExecutionTiming: (executionMs: number) => `工具 ${executionMs} ms`,
  stepNoResult: '等待执行结果',
  stepStatusPlanned: '已规划',
  stepStatusRunning: '执行中',
  stepStatusExecuted: '已执行',
  stepStatusFailed: '失败',
  stepStatusDone: '完成',
  stepStatusAwaitingReview: '待确认',
  stepStatusTakeover: '需接管',
  none: '无',
  acknowledge: '确认',
  cancel: '取消',
  finish: '完成',
  execute: '执行',
  user: '用户',
  assistant: '助手',
  observation: '观察',
  taskComplete: '任务完成',
  runLog: '运行日志',
  clear: '清空',
  noEvents: '暂无事件',
  userMessage: '用户消息',
  userMessageQueued: '用户消息已排队',
} as const
