export const EN_US_COPY = {
  settings: 'Settings',
  closeSettings: 'Close settings',
  tutorial: 'Tutorial',
  openTutorial: 'Open tutorial',
  closeTutorial: 'Close tutorial',
  tutorialTitle: 'Quick start',
  tutorialIntro: 'Follow these steps to hand an Android control task to the agent.',
  tutorialSteps: [
    {
      title: 'Connect Android device',
      body: 'Enable USB debugging, plug in the phone, then click Connect in the device panel and authorize ADB on the phone.',
    },
    {
      title: 'Configure model',
      body: 'Fill in Base URL, API Key, and Model in model settings, then choose the action protocol that matches the model.',
    },
    {
      title: 'Send a task',
      body: 'Type a concrete goal in chat, such as opening Settings and entering Wi-Fi; sending captures the screen and asks for the next action.',
    },
    {
      title: 'Watch and take over',
      body: 'Review pending actions, step details, and the run log while it runs; take over manually for sensitive flows or verification codes.',
    },
  ],
  tutorialNotesTitle: 'Good habits',
  tutorialNotes: [
    'Start with a simple task to confirm screenshots, coordinates, and text input all work.',
    'Keep human confirmation enabled for login, payment, deletion, authorization, and other high-risk flows.',
    'Edit App Cards in settings for common apps; Secrets and Custom Tools stay in this local browser.',
  ],
  tutorialFaqTitle: 'FAQ',
  tutorialFaqItems: [
    {
      question: 'What should I do if the device will not connect?',
      answer:
        'If the connection fails, run adb kill-server in your terminal, then reconnect the device. Also confirm WebUSB support, enable USB debugging, and approve the prompt on the phone.',
    },
    {
      question: 'Why does the agent stop before running?',
      answer:
        'Check Base URL, API Key, Model, and action protocol. You can also run Doctor to inspect model and device connectivity.',
    },
    {
      question: 'What if taps land in the wrong place?',
      answer:
        'Capture a fresh screenshot first and confirm the preview is current. The app maps model screenshot coordinates back to the native device screen before execution.',
    },
    {
      question: 'What if Chinese text or clearing text fails?',
      answer:
        'Use Enable ADB text input to install or enable ADB Keyboard, then enable Use ADB Keyboard for text in the left-side device options.',
    },
    {
      question: 'How are login, payment, and verification-code flows handled?',
      answer:
        'Keep sensitive action confirmation enabled. Take over manually for passwords, verification codes, payments, deletion, and authorization steps.',
    },
  ],
  agentContextRestored: 'Agent context restored',
  agentContextRestoreSkipped: 'Agent context restore skipped',
  connectDeviceTask: 'Connect device',
  captureScreenTask: 'Capture screen',
  deviceConnected: 'Device connected',
  deviceDisconnected: 'Device disconnected',
  disconnectDeviceTask: 'Disconnect device',
  executeActionTask: 'Execute action',
  executedAction: (preview: string) => `Executed ${preview}`,
  failedAction: (preview: string) => `Failed ${preview}`,
  failedToDownloadAdbKeyboard: (status: number) =>
    `Failed to download ADB Keyboard APK: HTTP ${status}.`,
  language: 'Language',
  languageSystem: 'System default',
  languageChinese: '中文',
  languageEnglish: 'English',
  appDescription:
    'Browser-based Android automation console for WebADB and OpenAI-compatible vision models.',
  githubRepository: 'GitHub repository',
  repositoryStats: 'Repository stats',
  stars: 'Stars',
  forks: 'Forks',
  openIssues: 'Open issues',
  githubStatsError: 'Could not load GitHub stats right now.',
  theme: 'Theme',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  localCache: 'Local cache',
  localCacheUsage: 'Local cache usage',
  localCacheLoading: 'Checking...',
  localCacheUnavailable: 'Unavailable in this browser',
  localCacheError: 'Could not read cache usage',
  localCacheUsageOf: (usage: string, quota: string) => `${usage} of ${quota}`,
  localCacheUsageOnly: (usage: string) => `${usage} used`,
  dataManagement: 'Data management',
  dataManagementShort: 'Data',
  settingsPreferences: 'Preferences',
  settingsPreferencesShort: 'Prefs',
  settingsResources: 'Resources',
  settingsResourcesShort: 'Res',
  settingsProjectInfo: 'Project',
  settingsProjectInfoShort: 'Proj',
  appVersion: 'Version',
  clearChatHistory: 'Clear chat history',
  clearRunLog: 'Clear run log',
  chatHistoryCleared: 'Chat history cleared',
  appCards: 'App cards',
  appCardsJson: 'App cards JSON',
  resetAppCards: 'Reset',
  secrets: 'Secrets',
  secretsJson: 'Secrets JSON',
  customTools: 'Custom tools',
  customToolsJson: 'Custom tools JSON',
  actionTools: 'Action tools',
  actionToolsHelp:
    'Turn individual tools on or off. Disabled tools are hidden from the model and blocked if a queued action still tries to run them.',
  actionToolEnabled: 'Enabled',
  actionToolDisabled: 'Disabled',
  actionToolToggle: (name: string) => `Toggle ${name}`,
  actionToolsSummary: (enabled: number, total: number) => `${enabled}/${total} enabled`,
  actionToolSearch: 'Search action tools',
  actionToolSearchPlaceholder: 'Search tools...',
  actionToolSearchClear: 'Clear tool search',
  actionToolFilter: 'Action tool filter',
  actionToolFilterAll: 'All',
  actionToolFilterEnabled: 'Enabled',
  actionToolFilterDisabled: 'Disabled',
  noActionToolSearchResults: (query: string) => `No tools match "${query}"`,
  noActionToolsInFilter: (filter: 'all' | 'disabled' | 'enabled') =>
    filter === 'disabled' ? 'No disabled tools.' : 'No tools in this view.',
  memory: 'Memory',
  memoryHelp:
    'Allow WebDroid to save short local facts from note/remember and reuse them in later tasks.',
  configurationPanel: 'Configuration',
  collapseConfigurationPanel: 'Collapse configuration panel',
  expandConfigurationPanel: 'Expand configuration panel',
  openConfigurationSection: (section: string) => `Open ${section}`,
  webUsbReady: 'ready',
  webUsbMissing: 'missing',
  model: 'Model',
  noModel: 'No model',
  modelSettings: 'Model settings',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  showApiKey: 'Show API key',
  hideApiKey: 'Hide API key',
  reasoningEffort: 'Thinking depth',
  reasoningEffortDefault: 'Provider default',
  reasoningEffortNone: 'None',
  reasoningEffortMinimal: 'Minimal',
  reasoningEffortLow: 'Low',
  reasoningEffortMedium: 'Medium',
  reasoningEffortHigh: 'High',
  reasoningEffortXHigh: 'Extra high',
  actionProtocol: 'Action protocol',
  actionProtocolWebDroidJson: 'WebDroid JSON',
  actionProtocolOpenAutoGlm: 'Open-AutoGLM function',
  actionProtocolMobilerunXml: 'mobilerun XML',
  streamModelResponses: 'Stream model responses',
  device: 'Device',
  noDevice: 'No device',
  deviceDetails: 'Device details',
  serial: 'Serial',
  currentApp: 'Current app',
  unknownApp: 'Unknown',
  package: 'Package',
  activity: 'Activity',
  keyboard: 'Keyboard',
  usbDebuggingRequired: 'USB debugging required',
  connect: 'Connect',
  adbConnectionHelpLabel: 'ADB connection help',
  adbConnectionHelpText:
    'If the connection fails, run adb kill-server in your terminal, then reconnect the device.',
  disconnect: 'Disconnect',
  capture: 'Capture',
  configureTextInput: 'Enable ADB text input',
  adbKeyboardConfigured: 'ADB text input enabled',
  tools: 'Tools',
  runDoctor: 'Run Doctor',
  doctorChecks: 'Doctor checks',
  doctorSummary: 'Doctor summary',
  installedApps: 'Installed apps',
  closeInstalledApps: 'Close installed apps',
  appSearch: 'App search',
  clearAppSearch: 'Clear app search',
  launchApp: 'Launch',
  launchInstalledApp: (name: string) => `Launch ${name}`,
  noInstalledApps: 'No installed apps found',
  noAppSearchResults: (query: string) => `No apps match "${query}"`,
  deviceOptions: 'Device options',
  directCommands: 'Direct commands',
  directCommand: 'Direct command',
  tapX: 'Tap X',
  tapY: 'Tap Y',
  runTap: 'Run Tap',
  swipeFromX: 'From X',
  swipeFromY: 'From Y',
  swipeToX: 'To X',
  swipeToY: 'To Y',
  runSwipe: 'Run Swipe',
  directText: 'Text',
  runType: 'Run Type',
  runBack: 'Back',
  runHome: 'Home',
  runEnter: 'Enter',
  screenBlackoutDuringAutoControl: 'Dim screen during auto control',
  screenBlackoutDuringAutoControlHelp:
    'Sets the Android brightness to 0 while an automatic run is active, then restores it afterward.',
  useAdbKeyboard: 'Use ADB Keyboard for text',
  confirmSensitiveActions: 'Confirm sensitive actions',
  unrestrictedMode: 'Unrestricted mode',
  sensitiveActionTitle: 'Sensitive action requested',
  sensitiveActionPrompt: 'Execute it?',
  actionSettle: 'Action settle (ms)',
  doubleTapInterval: 'Double tap interval (ms)',
  keyboardStep: 'Keyboard step (ms)',
  supportedActions: 'Supported actions',
  capabilities: [
    'Launch',
    'Tap',
    'Type',
    'Swipe',
    'Back',
    'Home',
    'Long press',
    'Double tap',
    'Wait',
    'Sequence',
    'Repeat',
    'Take over',
  ],
  actionNames: {
    back: 'Back',
    call_api: 'Call API',
    custom_tool: 'Custom tool',
    done: 'Done',
    double_tap: 'Double tap',
    home: 'Home',
    input_text: 'Input text',
    interact: 'Interact',
    key: 'Key press',
    launch: 'Launch',
    long_press: 'Long press',
    note: 'Note',
    open_url: 'Open URL',
    paste: 'Paste',
    repeat: 'Repeat',
    sequence: 'Sequence',
    set_clipboard: 'Set clipboard',
    swipe: 'Swipe',
    take_over: 'Take over',
    tap: 'Tap',
    type_secret: 'Type secret',
    view_screenshot: 'View screenshot',
    wait: 'Wait',
  },
  androidScreenshot: 'Android screenshot',
  expandedAndroidScreenshot: 'Expanded screenshot for Android screenshot',
  screenshotInteractionLayer: 'Screenshot interaction layer',
  runGeneratedAction: 'Run generated action',
  clearGeneratedAction: 'Clear generated action',
  openScreenshotFor: (title: string) => `Open screenshot for ${title}`,
  screenshotDialogFor: (title: string) => `Screenshot for ${title}`,
  closeScreenshotPreview: 'Close screenshot preview',
  screenshotZoomControls: 'Screenshot zoom controls',
  zoomInScreenshot: 'Zoom in screenshot',
  zoomOutScreenshot: 'Zoom out screenshot',
  resetScreenshotZoom: 'Reset screenshot zoom',
  showPhoneFullscreen: 'Show phone fullscreen',
  exitPhoneFullscreen: 'Exit phone fullscreen',
  fullscreenPhonePreview: 'Fullscreen phone preview',
  noScreenshot: 'No screenshot',
  noScreenshotHint: 'Connect and capture to show the live screen here',
  chat: 'Chat',
  history: 'History',
  openHistorySidebar: 'Open history sidebar',
  closeHistorySidebar: 'Close history sidebar',
  recentChats: 'Recent chats',
  historyEmpty: 'No chat history yet.',
  historyNoMatches: 'No matching chats.',
  historyNoMatchesForQuery: (query: string) => `No chats match "${query}"`,
  historySearchAria: 'Search chat history',
  historySearchPlaceholder: 'Search history...',
  historySearchClear: 'Clear history search',
  openHistoryThread: (title: string) => `Open chat ${title}`,
  deleteHistoryThread: (title: string) => `Delete chat ${title}`,
  conversation: 'Conversation',
  sessionState: 'Session state',
  sessionStatusIdle: 'Idle',
  sessionStatusRunning: 'Running',
  sessionStatusAwaitingReview: 'Needs review',
  sessionStatusAwaitingTakeover: 'Takeover',
  sessionStatusDone: 'Done',
  sessionStatusStopped: 'Stopped',
  sessionStatusError: 'Error',
  sessionStep: (step: number) => `Step #${step}`,
  queuedMessages: (count: number) => `${count} queued`,
  contextCompactedThroughStep: (step: number) => `Compacted through #${step}`,
  noMessages: 'No messages yet',
  quickStartPrompts: [
    'Open the Wi-Fi panel',
    'Capture and describe this screen',
    'Go back home',
  ],
  chatMessage: 'Chat message',
  chatPlaceholder: 'Send a follow-up instruction...',
  loopGuardStopped: 'Loop guard stopped the run',
  manualTakeoverRequested: 'Manual takeover requested',
  maxStepsReached: 'Max steps reached',
  send: 'Send',
  stopRun: 'Stop run',
  scrollToLatest: 'Scroll to latest',
  newChat: 'New chat',
  newChatStarted: 'New chat started',
  noAdbKeyboardDownloadSupport: 'This browser cannot download the ADB Keyboard APK.',
  typeMessageFirst: 'Type a message first.',
  runAgentTask: 'Run agent',
  screenBlackoutStartFailed: 'Could not dim the screen',
  screenBlackoutRestoreFailed: 'Could not restore screen brightness',
  runStopped: 'Run stopped',
  previousRunInterrupted: 'Previous run was interrupted before it finished.',
  waitForCurrentRun: 'Wait for the current run to finish.',
  maxSteps: 'Max steps',
  pendingAction: 'Pending action',
  screenCaptured: 'Screen captured',
  step: 'Step',
  stepPreview: (index: number, preview: string) => `Step ${index}: ${preview}`,
  stepAction: 'Action',
  stepResult: 'Result',
  stepDetails: 'Details',
  stepTool: 'Tool',
  stepExecutionResult: 'Execution result',
  stepModelOutput: 'Model output',
  stepParsedAction: 'Parsed action',
  stepTiming: (totalMs: number) => `Total ${totalMs} ms`,
  stepTimingSeconds: (seconds: number) => `${seconds} s`,
  stepTimingLessThanSecond: '<1 s',
  stepExecutionTiming: (executionMs: number) => `Tool ${executionMs} ms`,
  stepNoResult: 'Waiting for result',
  stepStatusPlanned: 'Planned',
  stepStatusRunning: 'Running',
  stepStatusExecuted: 'Executed',
  stepStatusFailed: 'Failed',
  stepStatusDone: 'Done',
  stepStatusAwaitingReview: 'Needs review',
  stepStatusTakeover: 'Takeover',
  none: 'None',
  acknowledge: 'Acknowledge',
  cancel: 'Cancel',
  finish: 'Finish',
  execute: 'Execute',
  user: 'User',
  assistant: 'Assistant',
  observation: 'Observation',
  taskComplete: 'Task complete',
  runLog: 'Run Log',
  clear: 'Clear',
  noEvents: 'No events yet',
  userMessage: 'User message',
  userMessageQueued: 'User message queued',
} as const
